version: '3'
services:
  relayer:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./config.toml:/config.toml
      - ./account_keys:/account_keys
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
